import { ZdInput } from '@zeedhi/vuetify';
import { SignatureInput } from '@zeedhi/zd-signature-input-common';
export default class ZdSignatureInput extends ZdInput {
    accept: string;
    backgroundColor: string;
    height: number | string;
    maxFileSize: number | string;
    maxWidth: number | string;
    minWidth: number | string;
    penColor: string;
    showUpload: boolean;
    hasSignatureValue: boolean;
    instance: SignatureInput;
    instanceType: typeof SignatureInput;
    private ignoreValueWatch;
    private resizeObserver;
    private resizeTimeout;
    private signaturePad;
    private strokeCommitTimeout;
    mounted(): void;
    beforeDestroy(): void;
    get canvasStyle(): {
        height: string;
    };
    get hideDetails(): boolean;
    get inactive(): boolean;
    get surfaceStyle(): {
        backgroundColor: string;
    };
    clearSignature(event?: Event): void;
    openFileInput(): void;
    handleFileChange(event: Event): Promise<void>;
    updatePenColor(value: string): void;
    updateBackgroundColor(value: string): Promise<void>;
    updateInputState(): void;
    handleHeightChange(): void;
    syncHeightProp(value: number | string): void;
    updateStrokeWidth(): void;
    handleInstanceValueChange(value: string): Promise<void>;
    private bindResize;
    private commitValue;
    private createSignaturePad;
    private fillBackground;
    private getCanvas;
    private getCanvasHeight;
    private getCanvasWidth;
    private handleStrokeEnd;
    private handleStrokeUpdate;
    private commitSignatureFromPad;
    private normalizeImage;
    private mountInputValidation;
    private readFileAsDataUrl;
    private redrawCurrentValue;
    private renderDataUrl;
    private resizeCanvas;
    private scheduleResize;
    private shouldPaintBackground;
    private toCssSize;
    private togglePadEvents;
    private unbindResize;
    private validateFile;
}
